### ISSUE TITLE
How generator_yellow.pkl is different from original stylegan?

### ISSUE THREAD

**Issue by mrgloom** [a312863063/seeprettyface-generator-yellow#5]
What is the difference between `generator_yellow.pkl` and original stylegan model?

**Comment by a312863063** [comment]
Hi, generator_yellow.pkl can only be used to generate the appearance of a yellow person. Its production method is fine-tuning based on the original model.

**Comment by wduo** [comment]
@a312863063 请问您是在Karras2019stylegan-ffhq-1024x1024.pkl模型之上，用黄种人数据进行调优训练的吗？调优所用数据集大概需要有多少图像呢？调优训练应该进行多少steps比较合适呢？期待您的回复。
